  import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class PlayerDataService {

  constructor() { }
  tempArray=[
    {
      "id":1,
      "profileAvatar":"/assets/player-avatar.svg",
      "firstName":"Justin",
      "lastName":"Time",
      "preferredName":"-",
      "gender":"Male",
      "dateOfBirth":"01 JAN 1999",
      "countryOfBirth":"England",
      "townOfBirth":"Harlow",
      "nationalities":"English",
      "nationalInsuranceNumber":"QQ123456F",
      "status":"Pending (FA & League)",
      "registrationType":"Scholarship",
      "registrationID":"#01231234",
      "registeringClub":"Manchester City",
      "player":"pending",
      "registration":"pending",
      "transfer":"pending",
      "intermediaries":"pending",
      "ITC":"pending",
      "GBE":"pending",
      "registrationDate":"01 Jul 2017",
      "registrationTime":"11:00 PM",
      "submittedDate":"01 Jul 2017",
      "submittedTime":"11:00 PM",
      "submittedBy":"Harry Pitt",
      "lastUpdatedDate":"01 Jul 2017",
      "lastUpdatedTime":"11:00 PM",
      "updatedBy":"Harry Pitt",
      "systemUpdated":"FAS",
      "assigneeShort":"NA",
      "assignee":"NA",
      "color":"NA"
    },
    {
      "id":2,
      "profileAvatar":"/assets/player-avatar.svg",
      "firstName":"Kevin Andrew",
      "lastName":"Clarke",
      "preferredName":"-",
      "gender":"Male",
      "dateOfBirth":"01 JAN 1999",
      "countryOfBirth":"England",
      "townOfBirth":"Harlow",
      "nationalities":"English",
      "nationalInsuranceNumber":"QQ123456F",
      "status":"On-hold",
      "registrationType":"Scholarship",
      "registrationID":"#01231233",
      "registeringClub":"Manchester City",
      "player":"approved",
      "registration":"approved",
      "transfer":"approved",
      "intermediaries":"approved",
      "ITC":"hold",
      "GBE":"NA",
      "registrationDate":"01 Jul 2017",
      "registrationTime":"05:31 PM",
      "submittedDate":"01 Jul 2017",
      "submittedTime":"05:31 PM",
      "submittedBy":"Harry Pitt",
      "lastUpdatedDate":"01 Jul 2017",
      "lastUpdatedTime":"05:31 PM",
      "updatedBy":"Harry Pitt",
      "systemUpdated":"FAS",
      "assigneeShort":"NA",
      "assignee":"NA",
      "color":"NA"
    },
    {
      "id":3,
      "profileAvatar":"/assets/player-avatar.svg",
      "firstName":"Justin",
      "lastName":"Time",
      "preferredName":"-",
      "gender":"Male",
      "dateOfBirth":"01 JAN 1999",
      "countryOfBirth":"England",
      "townOfBirth":"Harlow",
      "nationalities":"English",
      "nationalInsuranceNumber":"QQ123456F",
      "status":"Pending (FA)",
      "registrationType":"Minor Application",
      "registrationID":"#930",
      "registeringClub":"Manchester City",
      "player":"pending",
      "registration":"pending",
      "transfer":"NA",
      "intermediaries":"NA",
      "ITC":"NA",
      "GBE":"NA",
      "registrationDate":"01 Jul 2017",
      "registrationTime":"04:23 PM",
      "submittedDate":"01 Jul 2017",
      "submittedTime":"04:23 PM",
      "submittedBy":"Harry Pitt",
      "lastUpdatedDate":"01 Jul 2017",
      "lastUpdatedTime":"04:23 PM",
      "updatedBy":"Harry Pitt",
      "systemUpdated":"FAS",
      "assigneeShort":"NA",
      "assignee":"NA",
      "color":"NA"
    },
    {
      "id":4,
      "profileAvatar":"/assets/player-avatar.svg",
      "firstName":"Anthony",
      "lastName":"Hynes",
      "preferredName":"-",
      "gender":"Male",
      "dateOfBirth":"01 JAN 1999",
      "countryOfBirth":"England",
      "townOfBirth":"Harlow",
      "nationalities":"English",
      "nationalInsuranceNumber":"QQ123456F",
      "status":"Rejected",
      "registrationType":"Scholarship",
      "registrationID":"#01231212",
      "registeringClub":"Manchester City",
      "player":"rejected",
      "registration":"pending",
      "transfer":"NA",
      "intermediaries":"pending",
      "ITC":"NA",
      "GBE":"NA",
      "registrationDate":"01 Jul 2017",
      "registrationTime":"01:11 PM",
      "submittedDate":"01 Jul 2017",
      "submittedTime":"01:11 PM",
      "submittedBy":"Harry Pitt",
      "lastUpdatedDate":"01 Jul 2017",
      "lastUpdatedTime":"01:11 PM",
      "updatedBy":"Harry Pitt",
      "systemUpdated":"FAS",
      "assigneeShort":"NA",
      "assignee":"NA",
      "color":"NA"
    },
    {
      "id":5,
      "profileAvatar":"/assets/player-avatar.svg",
      "firstName":"Alexander",
      "lastName":"Hayward",
      "preferredName":"-",
      "gender":"Male",
      "dateOfBirth":"01 JAN 1999",
      "countryOfBirth":"England",
      "townOfBirth":"Harlow",
      "nationalities":"English",
      "nationalInsuranceNumber":"QQ123456F",
      "status":"Approved",
      "registrationType":"Scholarship",
      "registrationID":"#0000002",
      "registeringClub":"Wolverhampton Wanderers",
      "player":"approved",
      "registration":"approved",
      "transfer":"approved",
      "intermediaries":"approved",
      "ITC":"approved",
      "GBE":"approved",
      "registrationDate":"01 Jul 2017",
      "registrationTime":"11:04 AM",
      "submittedDate":"01 Jul 2017",
      "submittedTime":"11:04 AM",
      "submittedBy":"Harry Pitt",
      "lastUpdatedDate":"01 Jul 2017",
      "lastUpdatedTime":"11:04 AM",
      "updatedBy":"Harry Pitt",
      "systemUpdated":"FAS",
      "assigneeShort":"NA",
      "assignee":"NA",
      "color":"NA"
    },
    {
      "id":6,
      "profileAvatar":"/assets/player-avatar.svg",
      "firstName":"Joshua",
      "lastName":"Box",
      "preferredName":"-",
      "gender":"Male",
      "dateOfBirth":"01 JAN 1999",
      "countryOfBirth":"England",
      "townOfBirth":"Harlow",
      "nationalities":"English",
      "nationalInsuranceNumber":"QQ123456F",
      "status":"Pending (League)",
      "registrationType":"Academy",
      "registrationID":"#0000001",
      "registeringClub":"Manchester City",
      "player":"NA",
      "registration":"NA",
      "transfer":"NA",
      "intermediaries":"NA",
      "ITC":"approved",
      "GBE":"NA",
      "registrationDate":"01 Jul 2017",
      "registrationTime":"07:19 AM",
      "submittedDate":"01 Jul 2017",
      "submittedTime":"07:19 AM",
      "submittedBy":"Harry Pitt",
      "lastUpdatedDate":"01 Jul 2017",
      "lastUpdatedTime":"07:19 AM",
      "updatedBy":"Harry Pitt",
      "systemUpdated":"FAS",
      "assigneeShort":"NA",
      "assignee":"NA",
      "color":"NA"
    }
  ]
}
